apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # deployment labels
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  # these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  # this is pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers: 
      - name: user
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"
        command: ["sh", "-c", "echo 'failure' && exit 1"]
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits: 
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - ConfigMapRef:
            name: user